repos:
  - repo: local
    hooks:
      - id: readme-i18n-check
        name: Check README translations
        entry: ./readme_i18n-hook.sh
        language: script
        stages: [pre-commit]  # pre-commit hook only